{{- if .Values.persistence.worker.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ template "erpnext.name" . }}
    chart: {{ template "erpnext.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.persistence.worker.existingClaim }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.worker.size | quote }}
  storageClassName: {{ required "A valid persistence.worker.storageClass entry required!" .Values.persistence.worker.storageClass }}
{{- end }}
