{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.auth | toJson | b64enc }}
type: kubernetes.io/dockerconfigjson
{{- end }}