{{- if .Values.mariadb.enabled }}
apiVersion: v1
data:
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  mariadb-username: {{ .Values.mariadb.auth.username | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  mariadb-replication-password: {{ .Values.mariadb.auth.replicationPassword | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.mariadb.auth.existingSecret }} 
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}