apiVersion: v2
name: qdiak-deps
description: Dependency chart that sets up volume permissions and persistence layer for QDIak main chart
type: application
version: 0.1.0

dependencies:
- alias: redis-cache
  condition: redis-cache.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.0
- alias: redis-queue
  condition: redis-queue.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.0
- alias: redis-socketio
  condition: redis-socketio.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.0
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 10.3.3
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.0.3
# - alias: nfs-server
#   name: nfs-server-provisioner
#   repository: https://charts.helm.sh/stable
#   version: 1.1.3


appVersion: "1.16.0"
