apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erpnext.fullname" . }}-nginx
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erpnext.name" . }}-nginx
      app.kubernetes.io/instance: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erpnext.name" . }}-nginx
        app.kubernetes.io/instance: {{ .Release.Name }}-nginx
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "erpnext.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          env:
            - name: "BACKEND"
              value: {{ print (include "erpnext.fullname" .) "-gunicorn:" .Values.backend.service.port }}
            - name: "SOCKETIO"
              value: {{ print (include "erpnext.fullname" .) "-socketio:" .Values.socketio.service.port }}
            - name: "UPSTREAM_REAL_IP_ADDRESS"
              value: {{ .Values.frontend.environment.upstreamRealIPAddress | quote }}
            - name: "UPSTREAM_REAL_IP_RECURSIVE"
              value: {{ .Values.frontend.environment.upstreamRealIPRecursive | quote }}
            - name: "UPSTREAM_REAL_IP_HEADER"
              value: {{ .Values.frontend.environment.upstreamRealIPHeader }}
            - name: "FRAPPE_SITE_NAME_HEADER"
              value: {{ .Values.frontend.environment.frappeSiteNameHeader }}
          image: "{{ .Values.frontend.deployment.image.repository }}:{{ .Values.frontend.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
          - name: sites-dir
            mountPath: /usr/share/nginx/html/sites
          {{- if .Values.nginx.config }}
          - name: nginx-config
            mountPath: /etc/nginx/templates
          {{- end }}
      volumes:
        - name: sites-dir
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.frontend.deployment.image.nginxConfig }}
        - name: nginx-config
          configMap:
            name: {{ include "erpnext.fullname" . }}-nginx-config
        {{- end }}
      {{- with .Values.frontend.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.frontend.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
