# Main helmfile for QDIAK bundle.
# Define separate environments for different deployment targets

#######################################################################################################################################

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: frappe 
  url: https://helm.erpnext.com

helmDefaults:
  historyMax: 20
  createNamespace: true
  recreatePods: false # maybe it should be turned off

commonLabels:
  # qdiak-app is the top lvl descriptor of which app a resource belongs to
  # currently the only app is qdiak which is the main site
  qdiak-app: qdiak

environments: 
  default: {}
  frappe: {}
  qdiak-test: {}

releases:
- chart: ./qdiak
  installed: true
  name: qdiak-{{- .Environment.Name }}
  namespace: qdiak-{{- .Environment.Name }}
  timeout: 1800 # 30mins due to initial install job taking extremely long
  cleanupOnFail: true
  values:
  - '_values/values.yaml'
  - '_values/values.{{- .Environment.Name }}.yaml'
  secrets:
  - '_secrets/secrets.{{- .Environment.Name }}.yaml'
  needs:
  - 'qdiak-deps-{{- .Environment.Name }}'
  - nfs-server/nfs-server
- chart: ./qdiak-deps
  installed: true
  name: qdiak-deps-{{- .Environment.Name }}
  namespace: qdiak-{{- .Environment.Name }}
  timeout: 300
  cleanupOnFail: true
  values:
  - '_values/values.yaml'
  - '_values/values.{{- .Environment.Name}}.yaml'
  secrets:
  - '_secrets/secrets.{{- .Environment.Name }}.yaml'
  needs:
  - nfs-server/nfs-server
  # hooks:
  #   - events: ["postuninstall"]
  #     showlogs: true
  #     # Causes issues with finalizers and namespace usually doesnt get deleted
  #     command: kubectl
  #     args: ["delete", "ns", "qdiak-{{- .Environment.Name }}"]

- chart: stable/nfs-server-provisioner
  installed: true
  name: nfs-server
  namespace: nfs-server
  cleanupOnFail: true
  values:
    - persistence:
        enabled: true
        storageClass: do-block-storage
        size: 200Gi
