repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: frappe 
  url: https://helm.erpnext.com

helmDefaults:
  historyMax: 20
  createNamespace: true
  recreatePods: false # maybe it should be turned off

commonLabels:
  # qdiak-app is the top lvl descriptor of which app a resource belongs to
  # currently the only app is qdiak which is the main site
  qdiak-app: qdiak

environments: 
  default:

helmfiles:
  - path: helmfile.nfs.yaml

releases:
- chart: ./qdiak-deps
  installed: true
  name: qdiak-deps-{{- .Environment.Name }}
  namespace: qdiak-{{- .Environment.Name }}
  timeout: 300
  cleanupOnFail: true
  values:
  - 'values.default.yaml'
  secrets:
  - 'secrets/secrets.{{- .Environment.Name }}.yaml'