repositories:
- name: stable
  url: https://charts.helm.sh/stable

helmDefaults:
  createNamespace: true

commonLabels:
  # qdiak-app is the top lvl descriptor of which app a resource belongs to
  # currently the only app is qdiak which is the main site
  qdiak-app: qdiak
  cloud: do

releases:
- chart: stable/nfs-server-provisioner
  installed: true
  name: nfs-server
  namespace: nfs-server
  cleanupOnFail: true
  values:
    - persistence:
        enabled: true
        storageClass: do-block-storage
        size: 200Gi